"""Sweep Runner for automated experiment sets.

This module provides tools for running parameter sweeps
and generating families of related experiments.
"""

from __future__ import annotations

import copy
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterator

from core.config import Config, load_base_config
from core.registry import RunRegistry
from eval.benchmark import Benchmark


@dataclass
class SweepParameter:
    """A parameter to sweep over."""

    name: str
    values: list[Any]
    path: list[str] = field(default_factory=list)  # Nested path, e.g. ["model", "d_model"]

    def __post_init__(self):
        if not self.path:
            # Convert dot notation to path
            if "." in self.name:
                self.path = self.name.split(".")
            else:
                self.path = [self.name]

    def set_value(self, config_dict: dict[str, Any], value: Any) -> None:
        """Set parameter value in config dict."""
        d = config_dict
        for key in self.path[:-1]:
            if key not in d:
                d[key] = {}
            d = d[key]
        d[self.path[-1]] = value

    def get_value(self, config_dict: dict[str, Any]) -> Any:
        """Get parameter value from config dict."""
        d = config_dict
        for key in self.path:
            if key not in d:
                return None
            d = d[key]
        return d


@dataclass
class SweepConfig:
    """Configuration for a parameter sweep."""

    base_config_path: str
    sweep_id: str
    parameters: list[SweepParameter] = field(default_factory=list)
    seeds: list[int] = field(default_factory=lambda: [42])
    run_prefix: str = ""

    # Execution options
    dry_run: bool = False
    max_concurrent: int = 1
    continue_on_error: bool = True

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "SweepConfig":
        """Create from dictionary."""
        params = [
            SweepParameter(name=p["name"], values=p["values"], path=p.get("path", []))
            for p in d.get("parameters", [])
        ]
        return cls(
            base_config_path=d["base_config_path"],
            sweep_id=d["sweep_id"],
            parameters=params,
            seeds=d.get("seeds", [42]),
            run_prefix=d.get("run_prefix", ""),
            dry_run=d.get("dry_run", False),
            max_concurrent=d.get("max_concurrent", 1),
            continue_on_error=d.get("continue_on_error", True),
        )


@dataclass
class GeneratedRun:
    """A run generated by the sweep."""

    run_id: str
    config: dict[str, Any]
    parent_run_id: str | None = None
    seed: int = 42
    sweep_params: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "run_id": self.run_id,
            "config": self.config,
            "parent_run_id": self.parent_run_id,
            "seed": self.seed,
            "sweep_params": self.sweep_params,
        }


class SweepRunner:
    """Runner for parameter sweeps.

    Generates and optionally executes multiple runs
    by sweeping over specified parameters.
    """

    def __init__(self, config: SweepConfig, registry: RunRegistry | None = None):
        self.config = config
        self.registry = registry or RunRegistry()
        self.generated_runs: list[GeneratedRun] = []

    def generate_runs(self) -> list[GeneratedRun]:
        """Generate all runs for the sweep.

        Returns list of GeneratedRun objects.
        """
        # Load base config
        base_config = load_base_config(self.config.base_config_path)
        base_dict = base_config.to_dict()

        runs = []
        run_counter = 1

        # Generate all combinations
        param_combinations = list(self._param_combinations())

        for param_values in param_combinations:
            for seed in self.config.seeds:
                # Create config for this combination
                config_dict = copy.deepcopy(base_dict)

                # Apply parameter values
                sweep_params = {}
                for param, value in zip(self.config.parameters, param_values):
                    param.set_value(config_dict, value)
                    sweep_params[param.name] = value

                # Generate run ID
                run_id = self._generate_run_id(run_counter, param_values, seed)
                config_dict["run_id"] = run_id
                config_dict["seed"] = seed

                # Find parent run (if applicable)
                parent_run_id = self._find_parent_run(config_dict)

                run = GeneratedRun(
                    run_id=run_id,
                    config=config_dict,
                    parent_run_id=parent_run_id,
                    seed=seed,
                    sweep_params=sweep_params,
                )
                runs.append(run)
                run_counter += 1

        self.generated_runs = runs
        return runs

    def _param_combinations(self) -> Iterator[list[Any]]:
        """Generate all parameter value combinations using iterative product."""
        if not self.config.parameters:
            yield []
            return

        # Use iterative product for better performance
        import itertools
        
        # Extract value lists
        value_lists = [param.values for param in self.config.parameters]
        
        # Calculate total combinations for validation
        total = 1
        for values in value_lists:
            total *= len(values)
        
        # Warn if too many combinations
        if total > 1000:
            import warnings
            warnings.warn(
                f"Large sweep: {total} combinations. Consider reducing parameters.",
                UserWarning
            )
        
        # Generate using itertools.product (memory efficient)
        for combination in itertools.product(*value_lists):
            yield list(combination)

    def _generate_run_id(
        self,
        counter: int,
        param_values: list[Any],
        seed: int,
    ) -> str:
        """Generate a unique run ID."""
        parts = [self.config.run_prefix or self.config.sweep_id]

        # Add parameter abbreviations
        for param, value in zip(self.config.parameters, param_values):
            short_name = param.path[-1][:3]  # First 3 chars
            parts.append(f"{short_name}{value}")

        # Add seed if multiple seeds
        if len(self.config.seeds) > 1:
            parts.append(f"s{seed}")

        # Add counter
        parts.append(f"r{counter:03d}")

        return "_".join(str(p) for p in parts)

    def _find_parent_run(self, config_dict: dict[str, Any]) -> str | None:
        """Find parent run for this config."""
        # Simple heuristic: find run with same config minus one parameter
        # This could be made smarter based on sweep structure
        return None

    def execute_runs(self) -> dict[str, Any]:
        """Execute all generated runs.

        Returns execution summary.
        """
        if not self.generated_runs:
            self.generate_runs()

        summary = {
            "sweep_id": self.config.sweep_id,
            "total_runs": len(self.generated_runs),
            "executed": 0,
            "skipped": 0,
            "failed": 0,
            "results": [],
        }

        for run in self.generated_runs:
            if self.config.dry_run:
                print(f"[DRY RUN] Would execute: {run.run_id}")
                summary["skipped"] += 1
                continue

            # Save config
            config_path = Path(f"configs/runs/{run.run_id}.yaml")
            self._save_config(run.config, config_path)

            # Execute run
            try:
                result = self._execute_single_run(run)
                summary["executed"] += 1
                summary["results"].append({
                    "run_id": run.run_id,
                    "status": "completed",
                    "result": result,
                })
            except Exception as e:
                summary["failed"] += 1
                summary["results"].append({
                    "run_id": run.run_id,
                    "status": "failed",
                    "error": str(e),
                })

                if not self.config.continue_on_error:
                    break

        return summary

    def _save_config(self, config_dict: dict[str, Any], path: Path) -> None:
        """Save config to YAML file."""
        import yaml

        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w") as f:
            yaml.dump(config_dict, f, default_flow_style=False)

    def _execute_single_run(self, run: GeneratedRun) -> dict[str, Any]:
        """Execute a single run.

        Returns run result.
        """
        # Call the run module
        config_path = f"configs/runs/{run.run_id}.yaml"

        result = subprocess.run(
            ["python3", "-m", "runs.run", "--config", config_path],
            capture_output=True,
            text=True,
        )

        if result.returncode != 0:
            raise RuntimeError(f"Run failed: {result.stderr}")

        return {"returncode": result.returncode}

    def print_summary(self) -> str:
        """Print sweep summary."""
        lines = [
            "=" * 60,
            f"SWEEP: {self.config.sweep_id}",
            "=" * 60,
            f"Base config: {self.config.base_config_path}",
            f"Parameters: {len(self.config.parameters)}",
            f"Seeds: {self.config.seeds}",
            f"Total runs: {len(self.generated_runs)}",
            "",
            "Parameter ranges:",
        ]

        for param in self.config.parameters:
            lines.append(f"  {param.name}: {param.values}")

        lines.append("")
        lines.append("Generated runs:")
        for run in self.generated_runs[:10]:  # Show first 10
            lines.append(f"  - {run.run_id}")

        if len(self.generated_runs) > 10:
            lines.append(f"  ... and {len(self.generated_runs) - 10} more")

        lines.append("=" * 60)
        return "\n".join(lines)


def create_sweep(
    sweep_id: str,
    base_config: str,
    parameters: dict[str, list[Any]],
    seeds: list[int] | None = None,
    run_prefix: str = "",
) -> SweepRunner:
    """Convenience function to create a sweep.

    Args:
        sweep_id: Unique identifier for the sweep
        base_config: Path to base configuration
        parameters: Dict mapping parameter names to value lists
        seeds: List of seeds to use
        run_prefix: Prefix for run IDs

    Returns:
        Configured SweepRunner
    """
    sweep_params = [
        SweepParameter(name=name, values=values)
        for name, values in parameters.items()
    ]

    config = SweepConfig(
        base_config_path=base_config,
        sweep_id=sweep_id,
        parameters=sweep_params,
        seeds=seeds or [42],
        run_prefix=run_prefix,
    )

    return SweepRunner(config)
